services:
  - type: web
    name: royal-desi-ghee-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    buildFilter:
      paths:
        - "backend/**"
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
